# SPDX-FileCopyrightText: 2026 vikworks UG (haftungsbeschränkt)
#
# SPDX-License-Identifier: Apache-2.0

"""The model catalog as the hand-written registry and llm tables defined it.

Captured from the code the recipe files replaced, and never regenerated:
it is the fixed point the built-in recipes must reproduce field for field.
Change it only together with the recipe file whose value moves, and say why
in that commit.
"""

# Captured values, kept verbatim: the long weight paths stay on one line.
# ruff: noqa: E501

BUILTIN_SPECS = [
    {
        "aliases": (),
        "backend": "faster-whisper+pyannote",
        "detail": "transcribe + diarize",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": True,
        "mmproj": None,
        "model": "whisper-large-v3",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 4.0,
        "worker": "audio",
    },
    {
        "aliases": (),
        "backend": "transformers",
        "detail": "relative depth · ViT-S 25M · Apache-2.0 · fits beside anything",
        "engine": None,
        "label": "Depth Anything V2 Small",
        "lane_width": None,
        "max_batch": 8,
        "measured": True,
        "mmproj": None,
        "model": "depth-anything-v2-small",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 1.5,
        "worker": "depth",
    },
    {
        "aliases": (),
        "backend": "speechbrain",
        "detail": "speaker voiceprints",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": True,
        "mmproj": None,
        "model": "ecapa-tdnn",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 0.6,
        "worker": "embed",
    },
    {
        "aliases": (),
        "backend": "sd.cpp",
        "detail": "",
        "engine": "sd.cpp",
        "label": "",
        "lane_width": None,
        "max_batch": 4,
        "measured": True,
        "mmproj": None,
        "model": "flux_klein",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 8.0,
        "worker": "image_edit",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "gemma-3-27b-it-qat",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 18.0,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "chat · 128k ctx · 4 slots",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": True,
        "mmproj": None,
        "model": "gemma-4-12b",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 9.5,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "gemma-4-26b-a4b-it",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 18.0,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "gemma-4-31b-it",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 22.0,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "llama-3.2-3b",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 3.0,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "qwen-coder-30b",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 20.0,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "qwen3.5-35b-a3b",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 23.0,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "qwen3.6-27b",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 24.0,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "llama.cpp",
        "detail": "chat + vision · 128k ctx",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": 32,
        "measured": True,
        "mmproj": "unsloth-Qwen3.8-27B-GGUF/mmproj-F16.gguf",
        "model": "qwen3.8-27b",
        "resident_priority": None,
        "vision": True,
        "voices": (),
        "vram_gb": 26.5,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "vllm",
        "detail": "chat + vision · vllm · batch · 16 in parallel · 128k ctx",
        "engine": None,
        "label": "Qwen3.8 27B NVFP4",
        "lane_width": 16,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "qwen3.8-27b-nvfp4",
        "resident_priority": None,
        "vision": True,
        "voices": (),
        "vram_gb": 29.42,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "vllm",
        "detail": "chat + vision · vllm · MTP · fastest single request · 128k ctx",
        "engine": None,
        "label": "Qwen3.8 27B NVFP4 (interactive)",
        "lane_width": 4,
        "max_batch": 32,
        "measured": False,
        "mmproj": None,
        "model": "qwen3.8-27b-nvfp4-chat",
        "resident_priority": None,
        "vision": True,
        "voices": (),
        "vram_gb": 29.73,
        "worker": "llm",
    },
    {
        "aliases": (),
        "backend": "transformers",
        "detail": "layout + per-region recognition · tables as HTML · fits beside anything",
        "engine": None,
        "label": "GLM-OCR",
        "lane_width": None,
        "max_batch": 4,
        "measured": True,
        "mmproj": None,
        "model": "glm-ocr",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 4.0,
        "worker": "ocr",
    },
    {
        "aliases": (),
        "backend": "transformers-4.57",
        "detail": "PDF / page images → layout-tagged text · 32k ctx · dozens of pages per pass",
        "engine": None,
        "label": "Unlimited-OCR",
        "lane_width": None,
        "max_batch": 4,
        "measured": True,
        "mmproj": None,
        "model": "unlimited-ocr",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 9.0,
        "worker": "ocr",
    },
    {
        "aliases": ("base",),
        "backend": "faster-whisper",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": False,
        "mmproj": None,
        "model": "faster-whisper-base",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 0.5,
        "worker": "stt",
    },
    {
        "aliases": ("large-v3",),
        "backend": "faster-whisper",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": False,
        "mmproj": None,
        "model": "faster-whisper-large-v3",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 3.0,
        "worker": "stt",
    },
    {
        "aliases": ("medium",),
        "backend": "faster-whisper",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": False,
        "mmproj": None,
        "model": "faster-whisper-medium",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 2.0,
        "worker": "stt",
    },
    {
        "aliases": ("small",),
        "backend": "faster-whisper",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": False,
        "mmproj": None,
        "model": "faster-whisper-small",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 1.0,
        "worker": "stt",
    },
    {
        "aliases": ("tiny",),
        "backend": "faster-whisper",
        "detail": "",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": False,
        "mmproj": None,
        "model": "faster-whisper-tiny",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 0.5,
        "worker": "stt",
    },
    {
        "aliases": (),
        "backend": "sd.cpp",
        "detail": "",
        "engine": "sd.cpp",
        "label": "",
        "lane_width": None,
        "max_batch": 8,
        "measured": True,
        "mmproj": None,
        "model": "flux_klein",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 8.0,
        "worker": "text2image",
    },
    {
        "aliases": (),
        "backend": "sd.cpp",
        "detail": "",
        "engine": "sd.cpp",
        "label": "",
        "lane_width": None,
        "max_batch": 8,
        "measured": True,
        "mmproj": None,
        "model": "zimage",
        "resident_priority": None,
        "vision": False,
        "voices": (),
        "vram_gb": 13.0,
        "worker": "text2image",
    },
    {
        "aliases": ("kokoro-82m",),
        "backend": "kokoro",
        "detail": "loads on demand without evicting residents",
        "engine": None,
        "label": "",
        "lane_width": None,
        "max_batch": None,
        "measured": True,
        "mmproj": None,
        "model": "kokoro",
        "resident_priority": None,
        "vision": False,
        "voices": ("af_heart", "am_adam", "af_bella"),
        "vram_gb": 1.0,
        "worker": "tts",
    },
]

LLM_TABLES = {
    "MODEL_ALIAS": {"gemma-4-12b": "gemma-4-12b"},
    "MODEL_CACHE_TYPE_K": {
        "gemma-4-12b": "q8_0",
        "gemma-4-26b-a4b-it": "q8_0",
        "qwen3.8-27b": "q8_0",
    },
    "MODEL_CACHE_TYPE_V": {
        "gemma-4-12b": "q8_0",
        "gemma-4-26b-a4b-it": "q8_0",
        "qwen3.8-27b": "q8_0",
    },
    "MODEL_CTX_SIZE": {"gemma-4-12b": 131072, "qwen3.6-27b": 262144, "qwen3.8-27b": 131072},
    "MODEL_LOOP_GUARD": {},
    "MODEL_PARALLEL": {"gemma-4-12b": 4},
    "MODEL_PATHS": {
        "gemma-3-27b-it-qat": "~/.lmstudio/models/lmstudio-community/gemma-3-27B-it-qat-GGUF/gemma-3-27B-it-QAT-Q4_0.gguf",
        "gemma-4-12b": "unsloth-gemma-4-12B-it-qat-GGUF/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf",
        "gemma-4-26b-a4b-it": "unsloth-gemma-4-26B-A4B-it-GGUF/gemma-4-26B-A4B-it-UD-Q4_K_M.gguf",
        "gemma-4-31b-it": "unsloth-gemma-4-31B-it-GGUF/gemma-4-31B-it-Q4_K_M.gguf",
        "llama-3.2-3b": "~/.lmstudio/models/lmstudio-community/Llama-3.2-3B-Instruct-GGUF/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        "qwen-coder-30b": "~/.lmstudio/models/lmstudio-community/Qwen3-Coder-30B-A3B-Instruct-GGUF/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf",
        "qwen3.5-35b-a3b": "unsloth-Qwen3.5-35B-A3B-GGUF/Qwen3.5-35B-A3B-UD-Q4_K_XL.gguf",
        "qwen3.6-27b": "unsloth-Qwen3.6-27B-GGUF/Qwen3.6-27B-UD-Q5_K_XL.gguf",
        "qwen3.8-27b": "unsloth-Qwen3.8-27B-GGUF/Qwen3.8-27B-UD-Q6_K.gguf",
    },
    "MODEL_REASONING": {
        "gemma-4-12b": "template",
        "gemma-4-26b-a4b-it": "on",
        "qwen3.6-27b": "on",
        "qwen3.8-27b": "on",
    },
    "MODEL_REASONING_BUDGET": {},
    "MODEL_REQUEST_DEFAULTS": {
        "qwen-coder-30b": {
            "dry_allowed_length": 4,
            "dry_base": 1.75,
            "dry_multiplier": 0.8,
            "dry_penalty_last_n": 4096,
        },
        "qwen3.5-35b-a3b": {
            "dry_allowed_length": 4,
            "dry_base": 1.75,
            "dry_multiplier": 0.8,
            "dry_penalty_last_n": 4096,
            "min_p": 0.0,
            "reasoning_budget_tokens": 24576,
            "top_k": 20,
        },
        "qwen3.6-27b": {
            "dry_allowed_length": 4,
            "dry_base": 1.75,
            "dry_multiplier": 0.8,
            "dry_penalty_last_n": 4096,
            "min_p": 0.0,
            "reasoning_budget_tokens": 24576,
            "top_k": 20,
        },
        "qwen3.8-27b": {
            "dry_allowed_length": 4,
            "dry_base": 1.75,
            "dry_multiplier": 0.8,
            "dry_penalty_last_n": 4096,
            "min_p": 0.0,
            "reasoning_budget_tokens": 24576,
            "top_k": 20,
        },
    },
    "MODEL_SPEC_TYPE": {},
}

LLM_DEFAULTS = {
    "DEFAULT_CACHE_TYPE_K": "q4_0",
    "DEFAULT_CACHE_TYPE_V": "q4_0",
    "DEFAULT_CTX_SIZE": 131072,
    "DEFAULT_LOOP_GUARD": True,
    "DEFAULT_PARALLEL": 1,
    "DEFAULT_REASONING": "off",
    "DEFAULT_REASONING_BUDGET": None,
    "DEFAULT_REQUEST_DEFAULTS": {},
    "DEFAULT_SPEC_TYPE": None,
}
